### ISSUE TITLE
idea: Research API to collect data for Model Training

### ISSUE THREAD

**Issue by tikikun** [homebrewltd/research#33]
We want to:
- Offer free LLM api to community
- Build up open dataset
- Collecting feedback of research team model

Probably will be hosted on cloud

**Comment by dan-homebrew** [comment]
This is a very important initiative for Homebrew:

- Jan can offer a free Research API, with appropriate user warnings (and option to default to local)
- Jan can strengthen its core functionality, with a model that improves with time (e.g. personal AI use cases)

## Goal

Our Research API should push the envelope on several fronts, with the primary goal of supporting Jan as a "foundation model" for an open-source Siri use case. 

We have found models are still lacking in practical usage: 
- Speech input is still poor, relying on model chaining
- Practical integration (e.g. "check my email/calendar" function calling) are still very poor

We will need to build up open datasets, to have positive differentiation from base llama3.1 and other models. A few areas I can think of: 

- Speech Embeddings (possibly multi-language)
- Chain of Thought (i.e. highest possible intelligence for given model size)
- Tool Use/Function Calling (e.g. to enable Jan use cases = Web Search, RAG, etc)
- Long Context (on edge devices, or server inference)
- Multi-modality (e.g. vision)

Of course, more and more areas are added each month. I would like us to focus on having fun, train and interact with the community, and build up open datasets that benefit our users through better models. 

## Logistics

- We will need to decide if we are self-hosting this (i.e. A6000s in Taiwan) or if we are using a cloud
- There is also a lot of data collection logistics (e.g. thumbs up, thumbs down), and backup/replication
- We need to think through the privacy aspect very carefully: is there a way to offer this in Jan, which is privacy-focused?

**Comment by tikikun** [comment]
done
